import React, {useMemo, useState} from 'react';
import {
  Linking,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {Clipboard} from 'react-native/Libraries/Components/Clipboard/Clipboard';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {format} from 'date-fns';
import {SectionHeader} from '../../components/layout';
import {ConfirmationToast} from '../../components/ui';
import {useChildStore} from '../../store';
import {MOCK_CHILD} from '../../utils/mockData';
import {getAgeLabel, getDietLabel} from '../../utils/formatting';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../theme';

interface DoctorReportScreenProps {
  navigation: any;
}

const DoctorReportScreen: React.FC<DoctorReportScreenProps> = ({navigation}) => {
  const insets = useSafeAreaInsets();
  const child = useChildStore((s) => s.child) || MOCK_CHILD;
  const [showToast, setShowToast] = useState(false);

  const reportText = useMemo(
    () =>
      [
        'NUTRITION SUMMARY REPORT',
        `Generated by Poshan · ${format(new Date(), 'MMM d, yyyy')}`,
        '',
        `${child.name} · ${getAgeLabel(child.ageGroup)} · ${getDietLabel(child.dietType)}`,
        'Monitoring period: 8 weeks',
        '',
        'Flagged deficiencies',
        'Iron — flagged low. Dietary intervention started Mar 2, 2026.',
        'Estimated current intake: ~5.2mg/day vs 10mg daily requirement.',
        '',
        'Current dietary pattern',
        'Legumes (dal, chole, rajma): 4–5x/week · Iron HIGH',
        'Whole grains: 7x/week',
        'Dairy (curd): 5x/week · Calcium MOD',
        'Vegetables: 2–3x/week · LOW',
        'Fruits: 3x/week',
        '',
        '8-week change',
        'Accepted foods: 8 → 12 (+4). Iron-rich meals per week: 2 → 5.',
      ].join('\n'),
    [child.ageGroup, child.dietType, child.name],
  );

  const handleShare = async () => {
    await Share.share({message: reportText});
  };

  const handleWhatsApp = async () => {
    const url = `whatsapp://send?text=${encodeURIComponent(reportText)}`;

    try {
      const canOpen = await Linking.canOpenURL(url);

      if (canOpen) {
        await Linking.openURL(url);
      } else {
        await handleShare();
      }
    } catch {
      await handleShare();
    }
  };

  return (
    <View
      style={[
        styles.container,
        {paddingTop: insets.top, paddingBottom: insets.bottom},
      ]}>
      <View style={styles.topBar}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.backIcon}>←</Text>
        </TouchableOpacity>
        <Text style={styles.topBarTitle}>Share with Doctor</Text>
        <TouchableOpacity onPress={handleShare}>
          <Text style={styles.shareIcon}>↗</Text>
        </TouchableOpacity>
      </View>

      <View style={styles.banner}>
        <Text style={styles.bannerIcon}>✚</Text>
        <Text style={styles.bannerText}>
          This summary is for your doctor&apos;s reference only. It is not a
          diagnosis.
        </Text>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}>
        <View style={[styles.reportCard, Shadows.card]}>
          <View style={styles.reportHeaderRow}>
            <Text style={styles.reportEyebrow}>Nutrition Summary Report</Text>
            <Text style={styles.reportHeaderMeta}>
              Generated by Poshan · {format(new Date(), 'MMM d, yyyy')}
            </Text>
          </View>

          <View style={styles.reportSection}>
            <Text style={styles.childInfo}>
              {child.name} · {getAgeLabel(child.ageGroup)} ·{' '}
              {getDietLabel(child.dietType)}
            </Text>
            <Text style={styles.childInfoMeta}>
              Monitoring period: 8 weeks (Jan 26 – Mar 20)
            </Text>
          </View>

          <View style={styles.reportSection}>
            <SectionHeader label="Flagged deficiencies" variant="eyebrow" />
            <View style={styles.flagRow}>
              <View style={styles.redDot} />
              <Text style={styles.flagText}>
                Iron — flagged low, recorded Mar 2
              </Text>
            </View>
            <Text style={styles.flagMeta}>
              Dietary intervention started Mar 2. Estimated current intake:
              ~5.2mg/day vs 10mg daily requirement.
            </Text>
          </View>

          <View style={styles.reportSection}>
            <SectionHeader label="Current dietary pattern" variant="eyebrow" />
            {[
              ['Legumes (dal, chole, rajma)', '4–5x/week', 'Iron: HIGH', 'green'],
              ['Whole grains', '7x/week', '', 'neutral'],
              ['Dairy (curd)', '5x/week', 'Calcium: MOD', 'amber'],
              ['Vegetables', '2–3x/week', 'LOW', 'red'],
              ['Fruits', '3x/week', '', 'neutral'],
            ].map(([label, frequency, tag, tone]) => (
              <View key={label} style={styles.patternRow}>
                <Text style={styles.patternLabel}>{label}</Text>
                <Text style={styles.patternFrequency}>{frequency}</Text>
                {tag ? (
                  <View
                    style={[
                      styles.patternTag,
                      tone === 'green' && styles.patternTagGreen,
                      tone === 'amber' && styles.patternTagAmber,
                      tone === 'red' && styles.patternTagRed,
                    ]}>
                    <Text
                      style={[
                        styles.patternTagText,
                        tone === 'green' && styles.patternTagTextGreen,
                        tone === 'amber' && styles.patternTagTextAmber,
                        tone === 'red' && styles.patternTagTextRed,
                      ]}>
                      {tag}
                    </Text>
                  </View>
                ) : (
                  <View style={styles.patternTagSpacer} />
                )}
              </View>
            ))}
          </View>

          <View style={styles.reportSection}>
            <SectionHeader label="8-week change" variant="eyebrow" />
            <Text style={styles.changeText}>
              Accepted foods: 8 → 12 (+4). Iron-rich meals per week: 2 → 5.
            </Text>
          </View>
        </View>

        <View style={styles.exportSection}>
          <TouchableOpacity style={styles.primaryButton} onPress={handleShare}>
            <Text style={styles.primaryButtonText}>Share as PDF</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.outlinedButton}
            onPress={() => {
              Clipboard.setString(reportText);
              setShowToast(true);
            }}>
            <Text style={styles.outlinedButtonText}>Copy as text</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={styles.whatsappButton}
            onPress={handleWhatsApp}>
            <Text style={styles.whatsappButtonText}>Send via WhatsApp</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      <ConfirmationToast
        visible={showToast}
        message="Report copied as text"
        onHide={() => setShowToast(false)}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BG,
    paddingHorizontal: 16,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
  },
  backIcon: {
    fontSize: 22,
    color: Colors.TEXT_PRIMARY,
  },
  topBarTitle: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: 17,
    color: Colors.TEXT_PRIMARY,
  },
  shareIcon: {
    fontSize: 18,
    color: Colors.TEXT_SECONDARY,
  },
  banner: {
    marginHorizontal: -16,
    backgroundColor: Colors.ERROR_LIGHT,
    borderBottomWidth: 1,
    borderBottomColor: '#FECACA',
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  bannerIcon: {
    fontSize: 14,
    color: Colors.ERROR,
    marginTop: 1,
  },
  bannerText: {
    flex: 1,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: '#991B1B',
    lineHeight: 18,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  reportCard: {
    marginTop: 12,
    backgroundColor: Colors.SURFACE,
    borderRadius: BorderRadius.lg,
    padding: Spacing.base,
  },
  reportHeaderRow: {
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  reportEyebrow: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.xs,
    color: Colors.TEXT_SECONDARY,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  reportHeaderMeta: {
    marginTop: 4,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.xs,
    color: Colors.TEXT_MUTED,
  },
  reportSection: {
    paddingTop: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  childInfo: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.sm,
    color: Colors.TEXT_PRIMARY,
  },
  childInfoMeta: {
    marginTop: 4,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: Colors.TEXT_SECONDARY,
  },
  flagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: 6,
  },
  redDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.ERROR,
  },
  flagText: {
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.base,
    color: '#374151',
  },
  flagMeta: {
    marginTop: 8,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: Colors.TEXT_SECONDARY,
    lineHeight: 18,
  },
  patternRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  patternLabel: {
    flex: 1,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: '#374151',
  },
  patternFrequency: {
    width: 68,
    textAlign: 'center',
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: Colors.TEXT_SECONDARY,
  },
  patternTag: {
    borderRadius: BorderRadius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  patternTagGreen: {
    backgroundColor: Colors.AI_BUBBLE,
  },
  patternTagAmber: {
    backgroundColor: Colors.AMBER_LIGHT,
  },
  patternTagRed: {
    backgroundColor: Colors.ERROR_LIGHT,
  },
  patternTagText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.xs,
  },
  patternTagTextGreen: {
    color: Colors.PRIMARY,
  },
  patternTagTextAmber: {
    color: '#D97706',
  },
  patternTagTextRed: {
    color: '#991B1B',
  },
  patternTagSpacer: {
    width: 68,
  },
  changeText: {
    marginTop: 6,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: '#374151',
    lineHeight: 18,
  },
  exportSection: {
    marginTop: 16,
    gap: 8,
  },
  primaryButton: {
    height: 52,
    borderRadius: BorderRadius['2xl'],
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: Colors.TEXT_INVERSE,
  },
  outlinedButton: {
    height: 52,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    borderColor: Colors.TEXT_SECONDARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlinedButtonText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: Colors.TEXT_SECONDARY,
  },
  whatsappButton: {
    height: 52,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    borderColor: '#25D366',
    alignItems: 'center',
    justifyContent: 'center',
  },
  whatsappButtonText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: '#25D366',
  },
});

export default DoctorReportScreen;
