import React, {useState} from 'react';
import {ScrollView, Share, StyleSheet, Text, TouchableOpacity, View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {format} from 'date-fns';
import {ProgressBar, ConfirmationToast} from '../../components/ui';
import {SectionHeader} from '../../components/layout';
import {useProgressStore} from '../../store';
import {MOCK_WEEKLY_REPORT} from '../../utils/mockData';
import {
  BorderRadius,
  Colors,
  FontFamily,
  FontSize,
  Shadows,
  Spacing,
} from '../../theme';

interface WeeklyReportScreenProps {
  navigation: any;
}

const TONE_COLORS = {
  green: Colors.ACCENT,
  amber: Colors.AMBER,
  red: Colors.ERROR,
};

const WeeklyReportScreen: React.FC<WeeklyReportScreenProps> = ({navigation}) => {
  const insets = useSafeAreaInsets();
  const weeklyReport = useProgressStore((s) => s.weeklyReport) || MOCK_WEEKLY_REPORT;
  const saveWeeklyReport = useProgressStore((s) => s.saveWeeklyReport);
  const [showToast, setShowToast] = useState(false);

  const shareMessage = [
    `Week of ${format(new Date(weeklyReport.startDate), 'MMM d')} – ${format(
      new Date(weeklyReport.endDate),
      'MMM d',
    )}`,
    `Win: ${weeklyReport.winTitle}`,
    weeklyReport.poshanRead,
  ].join('\n\n');

  return (
    <View
      style={[
        styles.container,
        {paddingTop: insets.top, paddingBottom: insets.bottom},
      ]}>
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}>
        <View style={styles.headerStrip}>
          <TouchableOpacity onPress={() => navigation.goBack()}>
            <Text style={styles.backIcon}>←</Text>
          </TouchableOpacity>
          <Text style={styles.headerDate}>
            Week of {format(new Date(weeklyReport.startDate), 'MMM d')} –{' '}
            {format(new Date(weeklyReport.endDate), 'MMM d')}
          </Text>
          <Text style={styles.headerTitle}>Arjun&apos;s Weekly Nutrition Summary</Text>
          <Text style={styles.headerMeta}>
            Generated by Poshan · {weeklyReport.weeksIn} weeks in
          </Text>
        </View>

        <View style={styles.summaryGrid}>
          {[
            {label: 'meals logged', value: `${weeklyReport.mealsLogged}`},
            {
              label: 'suggestions tried',
              value: `${weeklyReport.suggestionsTried}`,
            },
            {
              label: 'new food accepted',
              value: `${weeklyReport.newFoodsAccepted}`,
            },
            {label: 'Iron', value: weeklyReport.ironStatus},
          ].map((item, index) => (
            <View
              key={item.label}
              style={[
                styles.summaryCell,
                index % 2 === 0 && styles.summaryCellRightBorder,
                index < 2 && styles.summaryCellBottomBorder,
              ]}>
              <Text style={styles.summaryLabel}>{item.label}</Text>
              <Text style={styles.summaryValue}>{item.value}</Text>
            </View>
          ))}
        </View>

        <View style={[styles.card, Shadows.card]}>
          <SectionHeader
            label="This week's win"
            variant="eyebrow"
            color={Colors.PRIMARY}
          />
          <Text style={styles.winTitle}>{weeklyReport.winTitle}</Text>
          <Text style={styles.winDescription}>{weeklyReport.winDescription}</Text>
          <View style={styles.progressWrap}>
            <ProgressBar
              value={weeklyReport.exposureCount / weeklyReport.exposureTarget}
              color={Colors.PRIMARY}
              height={6}
              label={`${weeklyReport.exposureCount} of ~${weeklyReport.exposureTarget} exposures`}
            />
          </View>
        </View>

        <View style={[styles.card, Shadows.card]}>
          <SectionHeader label="What you tried" variant="eyebrow" />
          {weeklyReport.whatYouTried.map((item) => (
            <View key={item.id} style={styles.triedRow}>
              <View
                style={[
                  styles.triedDot,
                  {backgroundColor: TONE_COLORS[item.tone]},
                ]}
              />
              <Text style={styles.triedLabel}>{item.label}</Text>
              <Text style={styles.triedOutcome}>{item.outcome}</Text>
            </View>
          ))}
        </View>

        <View style={styles.readCard}>
          <SectionHeader
            label="Poshan's read"
            variant="eyebrow"
            color={Colors.PRIMARY}
          />
          <Text style={styles.readText}>{weeklyReport.poshanRead}</Text>
        </View>

        <View style={[styles.card, Shadows.card]}>
          <SectionHeader label="Try this next week" variant="eyebrow" />
          {weeklyReport.nextWeekSteps.map((step, index) => (
            <View key={step} style={styles.nextStepRow}>
              <View style={styles.nextStepNumber}>
                <Text style={styles.nextStepNumberText}>{index + 1}</Text>
              </View>
              <Text style={styles.nextStepText}>{step}</Text>
            </View>
          ))}
        </View>
      </ScrollView>

      <View style={styles.bottomBar}>
        <TouchableOpacity
          style={styles.primaryButton}
          onPress={() => Share.share({message: shareMessage})}>
          <Text style={styles.primaryButtonText}>Share with partner</Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={styles.outlinedButton}
          onPress={() => {
            saveWeeklyReport(weeklyReport);
            setShowToast(true);
          }}>
          <Text style={styles.outlinedButtonText}>Save report</Text>
        </TouchableOpacity>
      </View>

      <ConfirmationToast
        visible={showToast}
        message="Weekly report saved"
        onHide={() => setShowToast(false)}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.BG,
  },
  scrollContent: {
    paddingBottom: 130,
  },
  headerStrip: {
    backgroundColor: Colors.PRIMARY,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
  },
  backIcon: {
    fontSize: 22,
    color: Colors.TEXT_INVERSE,
    marginBottom: Spacing.base,
  },
  headerDate: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.sm,
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  headerTitle: {
    marginTop: 6,
    fontFamily: FontFamily.DISPLAY,
    fontSize: FontSize['2xl'],
    color: Colors.TEXT_INVERSE,
  },
  headerMeta: {
    marginTop: 6,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.xs,
    color: 'rgba(255,255,255,0.5)',
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: Colors.SURFACE,
  },
  summaryCell: {
    width: '50%',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  summaryCellRightBorder: {
    borderRightWidth: 1,
    borderRightColor: Colors.BORDER,
  },
  summaryCellBottomBorder: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.BORDER,
  },
  summaryLabel: {
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.xs,
    color: Colors.TEXT_SECONDARY,
    textTransform: 'uppercase',
  },
  summaryValue: {
    marginTop: 4,
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: Colors.TEXT_PRIMARY,
  },
  card: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: Colors.SURFACE,
    borderRadius: BorderRadius.lg,
    padding: Spacing.base,
  },
  winTitle: {
    fontFamily: FontFamily.DISPLAY,
    fontSize: FontSize.xl,
    color: Colors.TEXT_PRIMARY,
  },
  winDescription: {
    marginTop: 6,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.sm,
    color: Colors.TEXT_SECONDARY,
    lineHeight: 20,
  },
  progressWrap: {
    marginTop: 10,
  },
  triedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  triedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  triedLabel: {
    flex: 1,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.base,
    color: '#374151',
  },
  triedOutcome: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.sm,
    color: Colors.TEXT_SECONDARY,
  },
  readCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: Colors.AI_BUBBLE,
    borderRadius: BorderRadius.lg,
    borderLeftWidth: 4,
    borderLeftColor: Colors.PRIMARY,
    padding: Spacing.base,
  },
  readText: {
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.base,
    color: '#374151',
    lineHeight: 25,
  },
  nextStepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  nextStepNumber: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  nextStepNumberText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.xs,
    color: Colors.TEXT_INVERSE,
  },
  nextStepText: {
    flex: 1,
    fontFamily: FontFamily.BODY,
    fontSize: FontSize.base,
    color: '#374151',
    lineHeight: 20,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: Colors.SURFACE,
    borderTopWidth: 1,
    borderTopColor: Colors.BORDER,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  primaryButton: {
    height: 52,
    borderRadius: BorderRadius['2xl'],
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: Colors.TEXT_INVERSE,
  },
  outlinedButton: {
    height: 52,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1,
    borderColor: Colors.BORDER,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlinedButtonText: {
    fontFamily: FontFamily.BODY_SEMIBOLD,
    fontSize: FontSize.base,
    color: Colors.TEXT_SECONDARY,
  },
});

export default WeeklyReportScreen;
